### ISSUE TITLE
issues updating IC50 plots

### ISSUE THREAD

**Issue by aminaddetia** [jbloomlab/SARS-CoV-2-RBD_MAP_clinical_Abs#14]
@jbloom After adding the new neut data, I keep running into the following error `MergeError: Merge keys are not unique in right dataset; not a many-to-one merge` when executing the `analyze_neuts.ipynb` notebook.

**Comment by jbloom** [comment]
@aminaddetia, I just pushed a new commit to your branch that fixed the problem. Main issue is that it is now necessary to groupby date as well as antibody now that we have dates with multiple measurements. I also updated plot to show bounds as point shapes, as we can no longer have dotted lines as bound is now different for different assay days.

Otherwise, things look great! Do you want to output a nice looking titer plot and save as both PNG and SVG too? Looks like right now you have code to do that, but no actual plot in repo.

Then I think we just leave this on branch until we get reviews back and update paper with it, does that sound good? I don't think we want to merge new data into main until we update paper to keep them in sync.

**Comment by aminaddetia** [comment]
@jbloom sounds good! I added the PNG and SVG plots to the repo.
